AllCops:
  Exclude:
    - Gemfile
    - vendor/bundle/**/*

CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: reduce
    collect: map
    find_all: select

Documentation:
  Enabled: false

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

PredicateName:
  NamePrefixBlacklist:
    - is_

StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

DotPosition:
  EnforcedStyle: leading

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/IndentHash:
  EnforcedStyle: consistent

Style/BracesAroundHashParameters:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
