Rails/ActionFilter:
  Enabled: false

Rails/FindBy:
  Enabled: false

Style/FormatString:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/DefaultScope:
  Enabled: false
