version: "3"
services:
  nginx:
    build: .
    networks:
      nginx_small_light:
        ipv4_address: 192.168.33.2
    ports:
      - ${NGINX_PORT}:80
      - 443
    environment:
      UPSTREAM_BASE_URL: http://192.168.33.1:${IMAGES_PORT}
  image_server:
    image: cannin/nodejs-http-server
    networks:
      nginx_small_light:
        ipv4_address: 192.168.33.3
    ports:
      - ${IMAGES_PORT}:8080
    volumes:
      - ./spec/fixtures:/home
    command: http-server -od --cors /home
networks:
    nginx_small_light:
        external:
            name: nginx_small_light
